### ISSUE TITLE
Missing URL decoding on adapter request from brain.

### ISSUE THREAD

**Issue by nklerk** [NEEOInc/neeo-sdk#10]
when the brain request the adapter handler, the request is URL encoded. the SDK doesnt decode this resulting in a crash.

When a device adapter is created with a name "POWER OFF"

The brain uses this URI to communicate with the handler.
GET device/apt-16c79afa417343dd0e30e775423a9ad70f82bda2/POWER%20OFF/default

the request is't decoded so the SDK cant find the handler.
<pre>Error: HANDLER_NOT_FOUND<br> &nbsp; &nbsp;at errorHandler neeo-sdk\lib\device\express\routes\deviceroute.js:12:15)<br> &nbsp; &nbsp;at neeo-sdk\lib\device\express\routes\deviceroute.js:30:5<br> &nbsp; &nbsp;at paramCallback (express\lib\router\index.js:404:7)<br> &nbsp; &nbsp;at param (express\lib\router\index.js:384:5)<br> &nbsp; &nbsp;at paramCallback (express\lib\router\index.js:401:21)<br> &nbsp; &nbsp;at neeo-sdk\lib\device\express\routes\deviceroute.js:24:3<br> &nbsp; &nbsp;at paramCallback (express\lib\router\index.js:404:7)<br> &nbsp; &nbsp;at param (express\lib\router\index.js:384:5)<br> &nbsp; &nbsp;at Function.process_params (express\lib\router\index.js:410:3)<br> &nbsp; &nbsp;at next (express\lib\router\index.js:275:10)<br> &nbsp; &nbsp;at Function.handle (express\lib\router\index.js:174:3)<br> &nbsp; &nbsp;at router (express\lib\router\index.js:47:12)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (express\lib\router\index.js:317:13)<br> &nbsp; &nbsp;at express\lib\router\index.js:284:7<br> &nbsp; &nbsp;at Function.process_params (express\lib\router\index.js:335:12)</pre>

**Comment by neophob** [comment]
fixed in the v0.37.0 NEEO SDK, feel free to reopen if the new version did not resolve this issue
