### ISSUE TITLE
Driver Export: single device vs multiple devices per driver

### ISSUE THREAD

**Issue by pfiaux** [NEEOInc/neeo-sdk#100]
Currently a server can start up multiple drivers, we don't plan to remove it in the short term to avoid breaking any drivers using that feature (see #82 & #92). That doesn't mean we can't move away from it mid/long term if single driver is a better option.

To avoid mixing this discussion with other ones i'm creating this issue, we'll summarize the arguments here in the description:

## Arguments for multiple drivers

* When running on embedded systems sharing between multiple drivers minimizes resource use (only 1 server, sharing of npm dependencies, ...)
* Multiple names for same controller (for example a Sonos Play 1 and Sonos Play 2 drivers use the same API, thus share the same code, thus 1 server is leaner)
* Shared code for similar controllers (for example a V1 devices has features A & B, V2 has A & B with the the same API plus feature C)
* Once the server is decoupled (#82), this will allow running multiple drivers as single drivers with some additional code.
* Avoids breaking changes, the feature is currently supported removing it is a major change

## Arguments for single drivers

* When running drivers separating each means they're isolated and it minimizes side effects of crashes (also restarting a driver doesn't require restarting others)
* Drivers isolated completely by process

**Comment by tmrobert8** [comment]
How about a third approach: hybrid where you can specify multiple drivers but each driver is run in it's own process (with a watchdog)

**Comment by neophob** [comment]
There are different requirements - which require different solutions:

- there are **constraint** devices (like a rpi) - where it make sense to run multiple drivers in parallel. as a driver instance with express and our SDK needs some memory.
- there are non constrains devices which have a lot of memory and cpu power, where it make sense to run each device independent

So if we provide both solutions, both main use cases can be addressed.

@tmrobert8 I would like to avoid a 3rd option - and the SDK should focus on the functionality and not provide functions already lot's of other tools provide

**Comment by Shepless** [comment]
@neophob I'm not sure having two approaches is the best idea for executing the drivers? Also, not sure if I'm taking this thread off topic? The main two options I see us having here is either forking into a new process for each driver or using something like `zone.js` to try and safeguard the execution of the driver in the same process. As I see it:

### Forked Process (Driver Has Its Own Server)
#### Pros
- Complete isolation from the host server and other drivers
- Very easy to implement auto restart functionality
- If the host dies, the drivers can live on independently
- This is a solved problem in the node.js arena (many libs and great support)
#### Cons
- The isolation from the single server instance means that we either have many servers (one per driver) or we'd need to maintain comms via post messages: parent <---> child
- Although drivers themselves will be lightweight, each driver brings the overhead of a complete node process and server along with it

### Zone.js (Single Instance Server)
#### Pros
- Single server, lower overheads
- Shared dependencies

#### Cons
- Not fully isolated and comes with no guarantees for failure safety
- Will be difficult to attempt a restart of a failed driver (e.g. re-requiring modules, cleaning them up etc.)

At the moment I'm swinging towards the Forked Process approach. This really reminds me of the Hass.io approach, where add-ons are actually docker containers and this runs on RPIs with no issues.

**Comment by pfiaux** [comment]
Given that the goal in #82 is to split the CLI, the server and the driver into separate modules. The user of the server (CLI, driver manager or script) can decide how to run each driver. Together or separate. The main idea is we move the responsibility and the choice out of the SDK.

By the driver export i mean how one module exports it's driver, defined as:
```
module.exports = {
  devices: [],
}
```
So yes in a way how to run multiple exports (single vs multiple server) is not the scope I intended to discuss here (but in #82), I'll update the summary here. Instead I wanted to scope the discussion on the module export:
* Do we keep devices as an array of multiple devices
* Do we keep it as an array (for functional reasons) but only ever read the first device
* Do we change it to device with a single object

Our intent with the device declaration is to provide a flexible light weight wrapper defining the capabilities exposed to the Brain and binding with the handling code. So if we want to change it to a single device then the driver implementer loses in flexibility.

For example if you want to see both Sonos Play:1 and Sonos Play:2 as search result when adding the device but only use one code base (and runtime) since it's the same API you can't do it anymore. So if we remove multiple devices per export we would need to replace that with other features (name aliases, discovery result dependent capabilities, and ...), but we do this refactoring i'm having trouble seeing what the benefits are over the current option of multiple devices.

**Comment by tmrobert8** [comment]
Ahh - I had a feeling we misunderstood your post.  Personally - I think this decision is rather minor issue and don't really care one way or the other.  If pressed, I'd continue with an array for multiple devices because you maintain compatibility and I'm sure someone, somewhere would have that need (although I can't see why - it always happens eventually).

**Comment by Shepless** [comment]
@pfiaux I'm not sure about this:

> Do we keep it as an array (for functional reasons) but only ever read the first device

If we're only ever pulling out the first device in the array then what functional programming would we be doing with the array? Also, the Sonos example you gave wouldn't work if you just pulled out the first device that was exported?

**Comment by pfiaux** [comment]
I meant that if you have multiple arrays of one device, if you do decide to combine them you can easily flat map or concatenate them or even filter (even tho it's not so useful).

For the Sonos example the way I see it you:
* Run a single server for that driver with both devices (they can share the run time, connection to the sonos API and ...)
* Run 2 servers, one with the Play:1 and one with the Play:2 both running the same code but in separate processes.

That's why I think it's a good example of a case when you might want to have one driver export multiple devices because there's obvious benefits resource wise to doing so.

**Comment by pfiaux** [comment]
We've released a new CLI and updated the documentation with the best practices in the next branch.
