### ISSUE TITLE
sorting of Shortcuts

### ISSUE THREAD

**Issue by carp3-noctem** [NEEOInc/neeo-sdk#104]
I'm not sure if this is setup via the SDK or if it is a general Fault in the Brain Code, but its a bit disturbing:
When adding Buttons to the NEEO Brain via the SDK some there is no consisted order. As example i first expose all NEEO Remote Hardkeys via the Buttongroup (VOLUME, Controlpad, Menu and Back, Channel Zapper and POWER) then i do all predefined Softkeys also via Groups (Numpad, Color Buttons, Transport, Transport Search, Transport Scan, Transport Skip, Record) and a single Button INFO.
These are then displayed as alphabetic order on the Apps Shorcut page but gets disturbed by single Buttons that are added seperatly (you can have a look into my Enigma2 driver [index.js](https://github.com/carp3-noctem/neeo-driver-enigma2/blob/master/devices/enigma2/index.js) for all the signle buttons.
BUT the Buttons i add seperatly uses the order i add them and are not sorted alphabetic and also intermixed with the Button Group. Bit hard to describe what exactly i mean. If you like to have further Infos, just ask for it, i don't can describe it better currently.

**Comment by neophob** [comment]
hi

not sure if I understand the issue correcty. but you can order the shortcuts in the shortcuts view.

**Comment by neophob** [comment]
will close as not related to the sdk

**Comment by pfiaux** [comment]
I checked it out, it looks like the shortcuts are not properly sorted on the settings screen when adding shortcuts for a given device.

As @neophob mentioned this isn't an SDK bug, I'll file a bug report internally that issue in the firmware.

**Comment by carp3-noctem** [comment]
I allready thought it is firmware related, but was unsure. Thanks for handling it!
