### ISSUE TITLE
Directory POST callback

### ISSUE THREAD

**Issue by tmrobert8** [NEEOInc/neeo-sdk#107]
I'm trying to integrate the directory type into my openHAB SDK and I'm hoping one of you might see some issue I'm missing.  I register my SDK, add the ACCESSORIE device with the DIRECTORY type capability - but when I click on it, the UI immediately says "The directory could not be browsed.  Please try again".  In wireshark, I can tell the brain is not even attempting to send back a post statement (like it does with the official SDK).  So I'm missing something and was hoping someone might have an idea.

Here's my registersdk JSON:
```
{"name":"openHAB-d6456f48-333e-4037-84ad-13203f33ef76","baseUrl":"http://192.168.1.188:8080/neeo/NEEO-a5056097"}
```
I know that works fine because all the other capabilities are being called back properly

When the brain adds the device - here is the JSON:
```
{
	"id": 0,
	"adapterName": "russound:zone:a3ff3e87:1:6",
	"type": "ACCESSOIRE",
	"manufacturer": "openHAB",
	"name": "Great Room (6)",
	"tokens": "",
	"setup": {
		
	},
	"deviceCapabilities": [],
	"device": {
		"name": "Great Room (6)",
		"tokens": [],
		"specificname": "Great Room (6)"
	},
	"specificname": "Great Room (6)",
	"capabilities": [{
		"name": "russound_zone_a3ff3e87_1_6_source-none",
		"label": "Source",
		"type": "directory",
		"path": "%2Fdevice%2Frussound%3Azone%3Aa3ff3e87%3A1%3A6%2Frussound_zone_a3ff3e87_1_6_source%2Fnone%2F1%2Fdirectory%2Factor"
	},
	{
		"name": "russound_zone_a3ff3e87_1_6_mute-none",
		"label": "Mute",
		"type": "switch",
		"path": "%2Fdevice%2Frussound%3Azone%3Aa3ff3e87%3A1%3A6%2Frussound_zone_a3ff3e87_1_6_mute%2Fnone%2F1%2Fswitch%2Factor",
		"sensor": "russound_zone_a3ff3e87_1_6_mute-none"
	},
	{
		"name": "russound_zone_a3ff3e87_1_6_mute-none",
		"label": "Mute",
		"type": "sensor",
		"path": "%2Fdevice%2Frussound%3Azone%3Aa3ff3e87%3A1%3A6%2Frussound_zone_a3ff3e87_1_6_mute%2Fnone%2F1%2Fswitch%2Fsensor",
		"sensor": {
			"type": "binary"
		}
	}]
}
```
You'll see the device has a DIRECTORY type capability pointing back to my encoded path (note: I've tried a raw simple path as well - doesn't work).

The brain accepts this device fine.  I then add the directory as a shortcut and when pressed - nothing happens (I never see the post callback in wireshark - seems like the brain has some issue prior to even trying to post).  Note: the mute switch that I included works just fine (I get the proper callbacks).

Don't know if this helps - but I've also attached my /v1/projects/home showing everything.  

Was really hoping if someone can help me with this as I can't seem to get it to work!

Thanks,
Tim

[v1projectshome.txt](https://github.com/NEEOInc/neeo-sdk/files/2145766/v1projectshome.txt)

**Comment by neophob** [comment]
@tmrobert8 can you point me to a repo with the code, so I can take a look?

**Comment by tmrobert8** [comment]
I could but it would take you a HUGE amount of time to dissect that code (15000+ lines of code now).  That's why I tried to show the JSON being exchanged since that's the communication medium.  If you want, I attached the wireshare between the brain, my openHAB SDK and your SDK

Remove the ".txt" extension of course.  Put in a display filter of "http and ip.addr == 192.168.1.104" to get just the communcation between my PC and the brain in question.

All calls going to port 6336 is your official SDK running the File Browser plugin.  All calls going to 8080 are the ones going to my openHAB SDK.

In the wireshark - I first add the file browser from the official SDK (3692-3702) then add my directory from openHAB (5319-5330).  I add both directories as a shortcut.  Click on the one from your official SDK (9228-9230) and then click on the one from my openHAB one (no POST is made)

[neeodirectory.pcapng.txt](https://github.com/NEEOInc/neeo-sdk/files/2145777/neeodirectory.pcapng.txt)

**Comment by tmrobert8** [comment]
Another note - when I use chrome boomerang plugin to post what I think should be coming from the brain - openHAB does receive it and process it.  So I'm I *think* it's not on the openHAB receiving side and I have my firewalls turned off (so the post should be getting through - atleast it's getting through on the offical SDK running on the same machine - so that makes sense that it's not a firewall issue)

**Comment by neophob** [comment]
just to be sure, did you try with a clean installation of the sdk? does the sdk example `fileBrowser` works as expected?

**Comment by tmrobert8** [comment]
Yes to both - the file browser in the offical SDK works fine (I get the post backs when clicking on the directory capability).  I'm just not getting any postbacks from my SDK version of the device and wireshark seems to think the brain isn't even sending the post (so there must be something in the way I'm formatting the path that is causing the brain an issue?)

**Comment by neophob** [comment]
I would try to isolate your issue - try to use the code from the `fileBrowser` example and add it to your driver, then step by step migrate it to your code until it breaks.

Also try to run your code with `DEBUG="neeo*" npm start` to see all debug messages

**Comment by tmrobert8** [comment]
This is a side effect to a different issue that I'm about to post - closing
