### ISSUE TITLE
[feature request] Favorites API

### ISSUE THREAD

**Issue by tmrobert8** [NEEOInc/neeo-sdk#110]
If you have an STB or TV, you can create favorites that will allow quick access to stations.  Works well but there is so many more opportunities that favorites could handle if we had some type of API/callback to handle them.

Here's two use cases:
1.  Streaming TV services (Sling TV/DirectTV Now/etc).  I watch all my TV through DirectTV Now - I'd love to be able to create favorites to quickly get to channels I watch through them.  However, there is no 'channel numbers' associated with them but there are HTTP calls that can be done that will bring them up.  I'd love to be able to add a 'ESPN' favorite that when pressed, calls back the SDK and allows me to execute the HTTP call to switch DirectTV now to ESPN
2. Radio favorites.  I have a Russound whole house audio system that supports favorites (specific radio stations, pandora/tunein/spotify channels, etc).  I'd love to have those appear on the remote and when pressed - shift over to the favorite on the Russound system.  Again - all I'd need is a favorite callback in the SDK and I can do whatever then.

Implementation wise - you could do something similar to the DIRECTORY type you just introduced (in fact, I'm abusing the directory type right now to do something similar [provide a list of choices]) since it has pretty close to the type of API that would be needed.  Maybe introduce a FAVORITES type that works the same way and is hooked into the UI properly..

**Comment by neophob** [comment]
absolutly, this might be one option.

I'll close as we track this here #52 and your use cases should be covered already there
