### ISSUE TITLE
Document Player requirements and make directories optional

### ISSUE THREAD

**Issue by neophob** [NEEOInc/neeo-sdk#113]
- Make sure directories are not needed 
- document what components the full-screen player must support

**Comment by tmrobert8** [comment]
If I might add to this - also hook sensors/items up via roles/tags to avoid naming issues

**Comment by pfiaux** [comment]
The next release includes a new helper `.addPlayerWidget({...})` to simplify adding the player, updated documentation and updated player example.

The queue directory will also be optional, for now the root directory will remain required.

For now the sensor/switch/sliders need specific names, until a feature like role/tags (#112) is implemented this will be a limitation.
