### ISSUE TITLE
Error in readme.md

### ISSUE THREAD

**Issue by tmrobert8** [NEEOInc/neeo-sdk#129]
In the debug section on the readme.md - you have:
```
neeoapi
  .startServer({
    brain: BRAIN_IP,
    name: 'debug-server',
    devices: [
      driver,
    ]
  })
```

You need to add a port number (which is required by startServer)

**Comment by MichaelKohler** [comment]
This was fixed in https://github.com/NEEOInc/neeo-sdk/pull/145 and will be part of the next release. Thanks!
