### ISSUE TITLE
remove duplicate buildBrainUrl

### ISSUE THREAD

**Issue by neophob** [NEEOInc/neeo-sdk#13]
*Issue*
`lib/device/brain/index.js` and `lib/recipe/index.js` both contains a buildBrainUrl function

*COS*:
- remove duplicate function, only one buildBrainUrl function

**Comment by neophob** [comment]
This might be a nice example for your first PR, hints:

- create new `urlbuilder.js` file in the lib directory
- export the `buildBrainUrl` function
- write tests to cover the two use cases where the passed parameter is a) a string and b) an object with the keys host and port
- get rid of the existing two `buildBrainUrl` functions and use the function from the `urlbuilder.js`

**Comment by nklerk** [comment]
This one can be closed.

**Comment by neophob** [comment]
yes indeed, thanks
