### ISSUE TITLE
When a driver is removed from the NEEO brain while the SDK isn't availeble the SDK code will crash next time it starts. 

### ISSUE THREAD

**Issue by nklerk** [NEEOInc/neeo-sdk#15]
In regards, to https://github.com/NEEOInc/neeo-sdk/pull/11 here is a proper issue submision.

When a driver is removed from the NEEO brain while the SDK isn't availeble, the SDK code will crash next time it starts with an unhandled exception.

```
Unhandled exception has occurred: Error
Error: COMPONENTNAME_NOT_FOUND
    at BrainNotificationMapping._findNotificationKey.Promise (...\neeo-sdk-examples\node_modules\neeo-sdk\lib\device\brain\notificationMapping.js:52:12)
    at module.exports.BrainNotificationMapping._findNotificationKey (...\neeo-sdk-examples\node_modules\neeo-sdk\lib\device\brain\notificationMapping.js:32:10)
    at BrainNotificationMapping.getNotificationKey.componentName._fetchDataFromBrain.then (...\neeo-sdk-examples\node_modules\neeo-sdk\lib\device\brain\notificationMapping.js:67:19)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

## To reproduce this issue follow these steps:

-Start the discoverable device example.
-Add the PRO device that is reachable (unique-device-id-001)
-Add all the components of the device as shortcuts and see the values changing by the example code.
-Stop the example SDK code.
-Remove the discoverable device from the neeo
-Start example script again. You will get the Unhandled exception has occurred: Error

**Comment by neophob** [comment]
Hi Niels

that's the expected behaviour. When the SDK tries to send a notification to the NEEO Brain, the SDK needs to find the event key of the registered device.
If the device is deleted from the NEEO Brain, there is of course no event key anymore - all what the SDK can do is inform the calling function, in our case the `sendComponentUpdate`function.

However there is was an issue that a rejected promise was catched - however it shouldn't. This will be fixed in the next release. Example output of the fixed complex example:

```
  neeo:device:brain:BrainNotificationMapping getNotificationKey power-slider unique-device-id-001 src-9cd7728f2f64e828ea7fbca3159dc3dc48ab5849 apt-9a0fc147222feca0e94a025f2ad896f0815d687a +2s
  neeo:device:brain:BrainNotificationMapping request url http://127.0.0.1:3000/v1/api/notificationkey/src-9cd7728f2f64e828ea7fbca3159dc3dc48ab5849/apt-9a0fc147222feca0e94a025f2ad896f0815d687a/unique-device-id-001 +0ms
  neeo:device:brain:BrainNotificationMapping getNotificationKey example-text unique-device-id-001 src-9cd7728f2f64e828ea7fbca3159dc3dc48ab5849 apt-9a0fc147222feca0e94a025f2ad896f0815d687a +0ms
  neeo:device:brain:BrainNotificationMapping request url http://127.0.0.1:3000/v1/api/notificationkey/src-9cd7728f2f64e828ea7fbca3159dc3dc48ab5849/apt-9a0fc147222feca0e94a025f2ad896f0815d687a/unique-device-id-001 +0ms
failed to send slider notification COMPONENTNAME_NOT_FOUND
failed to send text notification COMPONENTNAME_NOT_FOUND
```

thanks for the heads up @nklerk, I'll close this ticket.

**Comment by nklerk** [comment]
nice, this is exacly what is needed, sorry i couldn;t find it.
