### ISSUE TITLE
WARNING: no input commands defined!

### ISSUE THREAD

**Issue by nklerk** [NEEOInc/neeo-sdk#161]
I'm working with the #NEXT branch now, as you've said in the just closed "issue" the SDK will warn when no INPUTS are defined.

This is not a big deal but i'm currently working on a HDMI matrix hub IP driver. The driver is a dynamic driver and buttons (especially the input buttons) are assigned dynamically. this means that the initial offered driver state does't have any input's and will return a warning. 

WARNING! WARNING! WARNING! WARNING! WARNING! WARNING! WARNING! WARNING! WARNING! WARNING!
WARNING: no input commands defined! Your device might not work as desired, check the docs
deviceBuilder.ts:192

Is there anyway this check can be done after executing the dynamic driver assignment? that would make more sense i believe.

**Comment by nklerk** [comment]
P.S. the driver itself is working great, its just cosmetics and probably endusers that will be scared the shit out of them with the many WARNINGS!'s roflol.

**Comment by pfiaux** [comment]
Interesting, you're right if it's the exported driver stub, not the dynamic discovered ones the validation doesn't really apply.

How do you define the exported driver (the one with enableDynamicDeviceBuilder) do you set the type to HDMISWITCH? If you don't set the type does it still work but without the warning?

**Comment by nklerk** [comment]
I actually do set the device type. I’ll test it.

**Comment by nklerk** [comment]
The warnign is gone now. I've removed the device type from the driver and supplie it during the dynamic part. Thanks for the fast reply.

**Comment by pfiaux** [comment]
Reopen if you find some other issues related to this.

I'm not sure the icon will be set correctly in the search without a type. If that's the case it might be better to change the SDK to allow the type but not print the warning if enableDynamicDeviceBuilder is true.
