### ISSUE TITLE
neeo-sdk (0.52.18) won't install on windows.

### ISSUE THREAD

**Issue by nklerk** [NEEOInc/neeo-sdk#164]
I tested this on two Windows10 systems. and both wont install through git, Linux works without issues.
workaround is to extract the files locally and issue npm install .\path\

Installation fails with: 
C:\Users\ndkso\Desktop\test>npm install git+https://github.com/NEEOInc/neeo-sdk.git#next

or when included in a drivers package.json.

Error:
> neeo-sdk@0.52.18 prepack C:\Users\ndkso\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-d5b06d55
> npm i && npm run build

added 589 packages from 1370 contributors and audited 2819 packages in 20.498s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

> neeo-sdk@0.52.18 build C:\Users\ndkso\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-d5b06d55
> tsc && npm run copy:validate-lib

> neeo-sdk@0.52.18 copy:validate-lib C:\Users\ndkso\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-d5b06d55
> mkdir -p ./dist/lib/device/validation/vendor && cp ./src/lib/device/validation/vendor/validate.min.js ./dist/lib/device/validation/vendor/

The syntax of the command is incorrect.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! neeo-sdk@0.52.18 copy:validate-lib: `mkdir -p ./dist/lib/device/validation/vendor && cp ./src/lib/device/validation/vendor/validate.min.js ./dist/lib/device/validation/vendor/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the neeo-sdk@0.52.18 copy:validate-lib script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ndkso\AppData\Roaming\npm-cache\_logs\2018-12-11T18_50_29_981Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! neeo-sdk@0.52.18 build: `tsc && npm run copy:validate-lib`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the neeo-sdk@0.52.18 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ndkso\AppData\Roaming\npm-cache\_logs\2018-12-11T18_50_30_023Z-debug.log
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
npm ERR! premature close

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ndkso\AppData\Roaming\npm-cache\_logs\2018-12-11T18_50_30_065Z-debug.log

**Comment by MichaelKohler** [comment]
Yes, thanks @nklerk. Fully acknolwedged and I will have a look tomorrow.

**Comment by MichaelKohler** [comment]
@nklerk this AFAIK should only happen when installing from GitHub as that will run the build steps. Directly installing from NPM should work for now: `npm install neeo-sdk@next`

Does that work for you?

**Comment by nklerk** [comment]
It worked perfectly! thanks.

**Comment by MichaelKohler** [comment]
As it works perfectly through npm, the fix for this will be included in 0.53.x, not 0.52.20. Thanks for reporting it!
