### ISSUE TITLE
[DOC] registerSubscriptionFunction example is bogus

### ISSUE THREAD

**Issue by yoctopuce** [NEEOInc/neeo-sdk#169]
in  [NEEO SDK 0.51.13 doc ](https://neeoinc.github.io/neeo-sdk/#lib-device-devicebuilder.js-registersubscriptionfunction)

Example for _registerSubscriptionFunction_ was obviously copy/pasted from an other project, it uses an undefined _sendComponentUpdate_ call and comments are bit cryptic. Here is a fix suggestion:

```javascript
// Update sensor at some later point
if (updateCallbackReference) {
  updateCallbackReference({
    uniqueDeviceId: uniqueDeviceId, // "default" unless you used  enableDiscovery
    component: nameOfDeviceComponent, // name you gave to the component when adding it
    value: updatedSensorValue   // new value 
  });
}

**Comment by pfiaux** [comment]
Thanks for reporting. There's a lot of pending documentation improvements in the upcoming 0.52.x release, I'll check if this was already updated or if should updated the registerSubscriptionFunction doc as well.

**Comment by pfiaux** [comment]
OK we revised the documentation for registerSubscriptionFunction, example description and function parameters should be more clear now! It will be included in the next SDK release.
