### ISSUE TITLE
Device Update: Add driver versioning and updating of capabilities

### ISSUE THREAD

**Issue by nklerk** [NEEOInc/neeo-sdk#18]
When updating a SDK driver (adding/removing capabilities) its currently not possible to chose update driver like with "real" drivers. A similar feature would be nice.

**Comment by Krikroff77** [comment]
Hello !

Definitely a must-have option 👍

**Comment by splattner** [comment]
:+1:

**Comment by benzman81** [comment]
Same here. Have a driver with configurable buttons. If driver is used in need and I restart the drive with more buttons, then they are not added to neeo (maybe same with removal). This is definitely needed as I have to remove the driver and its recipes every time.

**Comment by bpruessm** [comment]
I am needing this as well... 👍

**Comment by carp3-noctem** [comment]
Are there any news on this one?
Without Updates, it is a bit heavy to perform checks during coding.
Thanks in advance

**Comment by pfiaux** [comment]
We're getting started on device updates for the SDK drivers. You'll be able to specify a version, on SDK start up the NEEO Brain will automatically run available updates.

The processes roughly will look like this:

1. SDK restarts with new version
2. NEEO Brain gets the registration and checks version
3. Added devices using an older version will try to run the update
    - All capabilities not currently in the device will be added.
    - Devices settings changes are updated
    - Changed capability settings will be detected and updated
    - Migrations of capabilities (changing "name" field, migration format to be defined)

This will be tackled in multiple steps, these might be added over multiple releases.

- [ ] Detect device version changes
- [ ] Add new capabilities to existing devices
- [ ] Update device settings (for example add alwaysOn or change timings)
- [ ] Update existing capabilities (for example label or slider range)
- [ ] Migrate capabilities (for example rename "PWR OM" to "POWER ON")

Note: out of scope update features for now:
* Updates to the device name, manufacturer and type
* Removing capabilities

**Comment by nklerk** [comment]
Won't getting the full data (like in the initial adding of the device) not solve all these steps at once?

**Comment by carp3-noctem** [comment]
Will this feature also cover the internal SDK drivers?
Means:
When e.g. Sonos brings a new device, will there be a way to update the sonos driver without the needs of a firmware update?

So basically I would like to see the update will also apply for internal SDK drivers, so a feature enhancement or new device coverage or new features can be implemented without the need of a firmware update from neeo side.

There is still the approach that one of the team members check the code before pushed to the user's but it would be helpful for the future to have this ability.

**Comment by pfiaux** [comment]
That's a good idea, currently however the devices provided on the NEEO Brain are bundled with the firmware. We might change this in the future but downloading driver updates is outside the scope of this issue.

A lot of the built-in devices will still benefit from this feature. If they are updated with new components as soon as the new firmware version is installed the new components will be available without having to remote and re-add the device.

Regarding @nklerk's comment getting the full definition is part of the solution, but then internal representation of the device needs to updated as well so it's a bit more complex.

**Comment by MichaelKohler** [comment]
This will be part of the next release: https://github.com/NEEOInc/neeo-sdk/blob/f3448ca00814945f6e2dcbd750f98de96acdc659/lib/device/devicebuilder.js#L58
