### ISSUE TITLE
Remove 'Recipes' start screen if multiple recipes are already there.

### ISSUE THREAD

**Issue by gvdhoven** [NEEOInc/neeo-sdk#188]
The recipes start screen (showing the "Recipes make sure your devices..." notification) should only be shown when there are no recipes yet on the remote. Else it is a useless 'next' i have to press...

**Comment by neophob** [comment]
Thanks for the report @Webunity 

As this issue is not related to the SDK I will close this. Please use planet.neeo.com to report issues with the product. Thanks!
