### ISSUE TITLE
Bug in routing

### ISSUE THREAD

**Issue by tmrobert8** [NEEOInc/neeo-sdk#23]
From express/server.js - you set the routes like
'/db' - routeDatabase
'/device' - routeDevice
'/' - routeDeviceRegistration

'/db/search' for device search
'/db/{0}' where device definition

'/device/xxx' - device discovery/set/get values

'/xxx' - adapter subscription

The problem really occurs with the last one - where 'xxx' is defined as '/:adapterName/yyy'

What if I was very bad and decided to name my adapter "db" or "device"?!?  Routing would get really screwed up since I was able to match a different route.  Same goes if you change the device ID to a string - then I could have a device id of "search" and screw that part up.

The routes should be more explicit - something like
'/db/search'
'/db/get'
'/device/discovery/xxx'
'/device/get/xxx'
'/device/set/xxx'
'/device/subscribe/xxx'
'/device/unsubscribe/xxx'

That way they 'dynamic' part of the route can't screw up your routing.

**Comment by neophob** [comment]
good catch @tmrobert8. definitive make sense yes

**Comment by bdauria** [comment]
Fixed in 0.49.2
