### ISSUE TITLE
Subscribe/Unsubscribe Capabilities

### ISSUE THREAD

**Issue by tmrobert8** [NEEOInc/neeo-sdk#24]
I really like that the SDK will subscribe/unsubscribe from the device.  However, for complex devices there needs to be a way to subscribe/unsubscribe from each capability. 

Example: let's say I have a complex device with say 50 capabilities.  Of those 50, only 10 are general and the other 40 are 'advanced' use (ie think about the 'unpair' on apple tv - won't be used often).   Now - some of those 40 may be resource intensive and we don't want to start up those notifications unless we know they will be used.

What would be nice is if the capability is used (in a recipe or shortcut), the brain will 'subscribe' to those capabilities (like it does the device) and 'unsubscribe' if removed

**Comment by neophob** [comment]
Hi @tmrobert8 

> there needs to be a way to subscribe/unsubscribe from each capability.

can you tell me a bit more about the motivation for that?

**Comment by tmrobert8** [comment]
Thought I did - but I'll make it more concrete.  A sony TV (using the xscalar service) will have somewhere in the ballpark of 150 capabilities.  About 10-15 of those are the most important ones and probably another 75 of those are secondary importance.  The way it is now - you 'subscribe' to a device (ie the sony tv) and then expect to receive updates to the capabilities via notifications.  Without knowing what capabilities the brain is actually using - I'd have to query all 150 items and potentially send 150 updates to the brain when something changes.

If the brain called a 'subscribe' for the capabilities it's actually using, then the notification process would be simplier and less resource hungry.

**Comment by neophob** [comment]
Ok got it. 

> I'd have to query all 150 items and potentially send 150 updates to the brain when something changes.

Why - you (or your adapter) can cache the state and push only actual changes to the Brain. And your adapter get notifications from the device and then you rely them to the Brain. The initial state is queried from the Brain and then you send only changes to the Brain.

**Comment by tmrobert8** [comment]
'push only actual changes to the Brain' - yes but it's querying for the actual changes is the issue.  To query all 150 would be about 60ish http calls.  Would be even worse on Russound - to fully reread the state takes about 180 TCP commands and Russound is really slow at processing - takes a full 30 seconds for a full state refresh (and I'm sure I'm really pegging Russound's processors while I'm doing it).

From the brain perspective you'll only get a few updates - but providing those few updates is the issue since I don't know what is being used or not.  If I knew what was bound (via subscribe/unsubcribe), I can streamline the backend processing.

Note: I'm kinda simulating it right now because the brain ask for initial state (so I kinda know what is being 'subscribed') - I just don't know if something is removed (ie unsubscribe) and I really like things to be explicit (ie a subscribe call rather than noticing a side effect to a get call).

**Comment by neophob** [comment]
updated SDK v0.50.3 fixes this, check out the next branch
