### ISSUE TITLE
Component Look and Feel

### ISSUE THREAD

**Issue by tmrobert8** [NEEOInc/neeo-sdk#29]
In addition to new widgets/components, would be nice to have variants to existing components.  Example - a switch could be represented as a toggle or could be represented as a push button.

If you wanted to go more general - would be nice to specify our own look and feel to each component...

**Comment by neophob** [comment]
Thanks @tmrobert8 for your suggestion.

about your example:
- Example - a switch could be represented as a toggle or could be represented as a push button.

you can define this yourself when you're creating the device - you could also do both (a switch might be easier in the ui, the buttons might be easier to us in the recipe).

About the specify "own look and feel" - this needs to be done in the main product and does not make sense to do that in the SDK.

**Comment by tmrobert8** [comment]
Patrick said to post non-SDK things here - this is one of them.

You missed a point I had - a push button is one whose state is 'pushed' when on (ie it remains in a pushed down state when on, a normal button state when off)
