### ISSUE TITLE
Brain or SDK bug with device type LIGHT and multiple sliders

### ISSUE THREAD

**Issue by chixxi** [NEEOInc/neeo-sdk#30]
Origin: https://planet.neeo.com/t/x1zhs6/brain-or-sdk-bug-with-device-type-light-and-multiple-sliders

When adding a light with a power switch and a dimmer slider. these are added to the grouped recipe named light as: <on/off> <dimmer slider>

When adding a light with multiple sliders, (dimmer, hue, saturation, etc.) one of the sliders and the on/off switch is added to the grouped recipe. not necessarily the <dimmer slider>.I ended up with a <on/off> <hue> combination and another time with a <on/off> <saturation> combination.

I'm not sure if this is caused by the Brain, Recipe or SDK so i included all these tags.

__

Can you tell me if this is SDK related, or should this go in JIIRA?

**Comment by neophob** [comment]
Thanks @chixxi for the report. The problem is not the SDK but in the Brain itself.
