### ISSUE TITLE
Add support for more device types like TV and AVR.

### ISSUE THREAD

**Issue by DarkCinema** [NEEOInc/neeo-sdk#31]
Right now the SDK only supports Lights and Accessories. I like to add a TV and AVR as an IP controlled device and use the favorite and volume control functions like we can on the build in devices.

**Comment by neophob** [comment]
Yes, technically there are no issues but the documentation (#6) is still open

**Comment by neophob** [comment]
Fixed upstream, i'll close as soon as we released an updated firmware
