### ISSUE TITLE
Data can't be blank

### ISSUE THREAD

**Issue by tmrobert8** [NEEOInc/neeo-sdk#32]
Mike - not necessarily a SDK issue but was hoping you can comment.  I have a pandora streaming device that I've created a text label to represent the currently playing album name.  However, when pandora goes to a commercial - the album name becomes blank (empty string).  The notification going to the brain is this:
{"type":"6273219938429698048:russound_source_26e9bb26_2_albumname","data":""}

However - I get the following error message back:
{"message":"Validation failed: {\"data\":[\"Data can't be blank\"]}","error":{}}

Is that correct?  Can we really not send a blank to a text label (to clear it out)?

Now that I think about the SDK - does it convert a blank to a "-" to get around this?

**Comment by neophob** [comment]
Agreed, empty data should be allowed

**Comment by neophob** [comment]
Fixed upstream, i'll close as soon as we released an updated firmware
