### ISSUE TITLE
Input fields

### ISSUE THREAD

**Issue by chixxi** [NEEOInc/neeo-sdk#38]
Could we get inout fields so that users can enter data during the setup or when configuring a device from within the neeo app? Would be much user friendlier if they could enter things like logins, ip's, authentication codes and so on without having to go change the actual code.

**Comment by neophob** [comment]
Thanks @chixxi 

- About entering IP's - that part should be handled in the SDK itself so the user can only selects an entry, see the discovery example
- Login will be added soon, thats definitive needed.
- do you have more details about the authentication codes example?

BR
Michael

**Comment by chixxi** [comment]
IP: I know that automatic detection of devices is the very best way to go. I don't have an example just yet, but I do think that automatic detection is not possible for all devices.

Authentication Code: I think some devices do not provide access based on a local API, some need to be controlled over the cloud. Very often you can then create authentication codes which allow access to the cloud. LIFX for example does this (They have a local API, but for example light groups may only be detected over the cloud).

**Comment by tmrobert8** [comment]
Just to add - there is ALOT of devices that can't be detected and discovered.  I think it would be REALLY useful to simply have this enhancement to allow general question/answer from a plugin.  Then the plugin can decide if it wants the user to specify an ip address, a login, a password or any other information it requires (which some need alot - Russound RNET plugin would need to know IP, port, controller # and zone # - none of those discoverable and all required to connect).

**Comment by neophob** [comment]
Agree - there are a lot of such devices. question is, where should that part handled? there are two options:

- Handle it by the user, the user needs to provide all needed information for each time
- Abstract this requirement and handle it in the SDK / user application. 

there are some requirements which the brain needs to handle (like login, which is already implemented) but entering an ip address is definitive something the user application should provide. there are multiple solutions for that (use env variables, predefined settings, use a known dns name ...).

to define tasks of the brain and of the SDK / user application more clearly:
- The brain needs to manage and use devices provided by the user application
- The user application needs to provide the needed information the brain requires

**Comment by neophob** [comment]
Closing as unclear, feel free to reopen if you think we need to further discuss
