### ISSUE TITLE
TextLabel option

### ISSUE THREAD

**Issue by tmrobert8** [NEEOInc/neeo-sdk#40]
I know you just fixed it so that the label on the textlabel shows on the remote but can we have an option on text labels to NOT include the label by default (like it was prior to the fix but on a textlabel by textlabel basis)?

Use case: music - would be really nice to show just the album name not "Album Name: xxx".  Likewise there are text labels that act more like titles - so I'd want something showing "Pandora" or "Spotify" or "DLNA" and not "Source: Pandora", "Source: Spotify", etc...

**Comment by neophob** [comment]
updated SDK v0.50.3 fixes this, check out the next branch
