### ISSUE TITLE
Image button

### ISSUE THREAD

**Issue by tmrobert8** [NEEOInc/neeo-sdk#41]
Now that we have images and buttons - any chance we can get an image button?  

Example: let say I'm putting together a [DIAL ](http://www.dial-multiscreen.org/) plugin.  DIAL will give me (among other things) the the application URL and the image URL.  I'd like to expose this to NEEO as a series of image buttons - where button shows the application's image URL and pressing the button will trigger off the applications URL.  So on the remote - it will show the NETFLIX image, the AMAZON image, etc - and pressing one of those starts the application on the DIAL device..

**Comment by neophob** [comment]
Agree, make sense.

**Comment by neophob** [comment]
@tmrobert8 - after thinking about this feature I think you want the same feature like we have today with the Favorites. you don't want to re-add the device each time a favorite change. 

So I close this as duplicate of #52 - feel free to reopen if you don't agree.

ps: and yes - images will be supported
