### ISSUE TITLE
ImageUrl behaviour on the remote

### ISSUE THREAD

**Issue by carosatig** [NEEOInc/neeo-sdk#50]
Hi,

I have noticed that the remote is refreshing the images every 30 seconds.
The issue however is that when looking at the logs on the driver, every refresh, I get 2 requests and for every request, it is downloading the image twice resulting in the image being downloaded 4 times every 30 seconds ...

**Comment by neophob** [comment]
thanks for your report. can you provide us with your sdk example? the image should only fetched when the image is not cached. which brain version do you use?

**Comment by carosatig** [comment]
Hi sure.

I am using the latest version of the firmwares.
The driver is for a video intercom so I am using server a handling dynamic requests so the cached image is refreshed every time; I only expected however 1 request to the controller per refresh and obviously only 1 request to the server as well ...

let me know if I am doing something wrong.

Thanks.

device declaration:
```javascript
const intercomDevice = neeoapi.buildDevice('D101S')
  .setManufacturer('DoorBird')
  .addAdditionalSearchToken('foo')
  .setType('LIGHT')

  // Then we add the capabilities of the device
  .addButton({ name: 'b-previous', label: 'Previous' })
  .addButton({ name: 'b-open', label: 'Open' })
  .addButton({ name: 'b-next', label: 'Next' })
  .addImageUrl({ name: 'last-image', label: 'Current image', size: 'large' }, controller.getLargeImageUri)
  .addButtonHander(controller.onButtonPressed);
```
controller:
```javascript
module.exports.getLargeImageUri = function getLargeImageUri() {
  var liveImgUri = 'http://';
  liveImgUri += ip.address();
  liveImgUri += currentFlag++;
  console.log(`[CONTROLER] ${Date.now()} img uri: ${liveImgUri}`);
  return liveImgUri;
};
```
server:
```javascript
const server = http.createServer((req, res) => {
  var _url = url.parse(req.url,true).pathname;
  console.log(`_url : ${_url}`);
  console.log(`pathname: ${url.parse(req.url,true).pathname}`)
  switch (_url) {
    case '/actions/getimg':

    http.request(Myurl, function(response) {
      var data = new Stream();
      response.on('data', function(chunk) {
        data.push(chunk);
      });

      response.on('end', function() {
        var img = data.read();
        res.writeHead(200, {'Content-Type': 'image/jpg' });
        res.end(img, 'binary')
        console.log(`new img pushed ${Date.now()}`);
      });
    }).end();
    break;
  }
});
```
Logs:
from driver:
[CONTROLER] 1510498190158 img uri: http://10.0.1.7:3000/actions/getimg?flag=50
[CONTROLER] 1510498190162 img uri: http://10.0.1.7:3000/actions/getimg?flag=51

from server:
_url : /actions/getimg
pathname: /actions/getimg
_url : /actions/getimg
pathname: /actions/getimg
new img pushed 1510498190313
new img pushed 1510498190321
_url : /actions/getimg
pathname: /actions/getimg
_url : /actions/getimg
pathname: /actions/getimg
new img pushed 1510498190891
new img pushed 1510498190906

**Comment by carosatig** [comment]
Just to give you the full story ...

This behaviour is when using the remote only; if I use the iOS app, it behaves as expected:

driver:
[CONTROLER] 1510503936882 img uri: http://10.0.1.7:3000/actions/getimg?flag=54

server:
_url : /actions/getimg
pathname: /actions/getimg
new img pushed 1510503936976

**Comment by carosatig** [comment]
A little more info ...

My remote is on the cradle charging for a couple of hours now ...
however, the requests keep coming every 30 seconds ...
This might explain why I need to charge it twice a week ...

**Comment by neophob** [comment]
I verified your issue, some comments:

- increasing the flag id in the `getLargeImageUri` is not ideal - increasing the id should be triggered from your logic (maybe by time) but not from the request itself (for example what happens if you have 3 users, each requests a different image)
- when the neeo brain prepares the data for the remote, the brain prefetches the image that the remote will display - thats why you see two requests. but this won't work if the url change for each request.

will check if I can reproduce "I get 2 requests and for every request, it is downloading the image twice resulting in the image being downloaded 4 times every 30 seconds"

**Comment by carosatig** [comment]
Hi thanks for that, I replaced the flag by 
```javascript
parseInt(Date.now()/1000)
```
 so keeping the image cashed for 1 second and it seems to be working.

**Comment by neophob** [comment]
great to hear @carosatig
