### ISSUE TITLE
[feature request] sensor device type

### ISSUE THREAD

**Issue by carosatig** [NEEOInc/neeo-sdk#51]
Hi,

I am making a doorbell driver and it would be nice if I could start the device recipe when someone rings on the door ...
The only way I can see that working so far would be to have the possibility of creating a sensor device that would trigger the recipe.

**Comment by carp3-noctem** [comment]
You can also Start a Recipe through the API Call. This should also work, if you Call it from your SDK Driver.
Documentation can be found here: https://planet.neeo.com/t/x1trmk/api-examples-to-get-started

**Comment by carosatig** [comment]
looks good thanks I'll use the REST call directly then ...
would be nice if these were exposed in the SDK  ;-)

request for sensor type still stands thou the more the merrier ...

**Comment by neophob** [comment]
If you want to create a device for common use, then creating a Sensor definitive is the solution. as the logic what should be triggered when should be in the Brain and not distributed between device and Brain.

To sum up:
- the device should expose all needed functions (sensors and actions)
- use the Brain to configure the device

**Comment by carosatig** [comment]
yes exactly ...
I was thinking of "starting" the device when someone rings on the door so it would be easy to just access it through the Home screen of the remote / check who is there and open the door.
This however would also require a different type of device since the light type I am currently using doesn't persist on the home screen.

**Comment by neophob** [comment]
Closing as not a bug or not an issue.

@carosatig You can also use an accessory device and add shortcuts to another device.

**Comment by carosatig** [comment]
not sure how an accessory device could help me in that case ...
The idea is to run a recipe when someone rings on the door (switch on a light for example) and the only way to trigger the recipe would be that the driver exposes a sensor.

**Comment by carosatig** [comment]
Sorry didn't see the addSensor ;-) ...

Thanks
