### ISSUE TITLE
Not Using correct Adapter Base IP

### ISSUE THREAD

**Issue by splattner** [NEEOInc/neeo-sdk#58]
The ipHelper uses the first non internal IPv4 Address which then is used to generate the Adapter BaseURL. So there might be cases, when this does not work. Multiple NIC's, inside Docker Container.

I created a possible fix for this. See #57

**Comment by neophob** [comment]
Thanks @splattner for your report and PR. This is already possible today, see function https://neeoinc.github.io/neeo-sdk/?q=start#lib-index.js-module.exports.startserver.

you can already pass the attribute `baseurl` in the `configuration` object. looks like a doc update would make sense. What you think?

**Comment by splattner** [comment]
Oh yeah, sure. Why haven't I saw this :)
It's anyway nicer to not use env Vars inside the SDK. This way you can use the evn Var to use in the `configuration` object.

:+1: for the doc update!

**Comment by neophob** [comment]
Thanks for verifying, doc update will be part of the next release
