### ISSUE TITLE
CURSOR ENTER/OK button does not trigger event when setType('DVD')

### ISSUE THREAD

**Issue by isolationism** [NEEOInc/neeo-sdk#59]
Discovered while creating custom device definitions for serial-controlled devices in my home theatre. 

The `CURSOR ENTER` event does not fire for either `.addButton({name: 'CURSOR ENTER'})` nor `.addButtonGroup('Controlpad')`. As soon as I switched to `.setType('MEDIAPLAYER')` with no other changes, the button resumed working just fine.

**Comment by neophob** [comment]
Hi @isolationism 

I tried to reproduce your issue using the simpleAccessory example (see https://github.com/NEEOInc/neeo-sdk-examples/tree/master/lib/device/simpleAccessory).

I changed the definition of the device:

```
const customLightDevice = neeoapi.buildDevice('Simple Accessory')
  .setManufacturer('NEEO')
  .addAdditionalSearchToken('foo')
  .setType('DVD')

  // Then we add the capabilities of the device
  .addButton({ name: 'button-a', label: 'Button A' })
  .addButton({ name: 'button-b', label: 'Button B' })
  .addButton({name: 'CURSOR ENTER'})
  .addButtonGroup('Color Buttons')
  .addButtonHandler(controller.onButtonPressed);

function startSdkExample(brain) {
  console.log('- Start server');
  neeoapi.startServer({
    brain,
    port: 6336,
    name: 'simple-accessory-one',
    devices: [customLightDevice]
  })
  .then(() => {
    console.log('# READY! use the NEEO app to search for "NEEO Accessory".');
  })
  .catch((error) => {
    //if there was any error, print message out to console
    console.error('ERROR!', error.message);
    process.exit(1);
  });
}
```

this works as it should. Can you provide a sample code that shows your issue?

How did you try to trigger the `CURSOR ENTER`? using the mobile app or the remote? using a shortcut?

thanks and BR
Michael

**Comment by isolationism** [comment]
The defect is with the physical buttons; when I use the 'widget' button on screen the Enter/OK command works fine. I've just now discovered a very similar defect trying to get my SqueezeBox to work as a `MEDIAPLAYER` accessory, except with the "Channel Zapper" buttons. Again, no matter how I define them in the source code, the _physical buttons_ never work. However, if I had a channel zapper widget, they work perfectly from the screen.

My code examples are real-world so they are an order of magnitude more complex than what you have here, but I can paste them if it helps.

**Comment by isolationism** [comment]
I should also add that there was additionally some strange behaviour with the channel zapper buttons being mapped to `FORWARD` and `REVERSE` even though there was no such definition anywhere in my file. Debugging problems with the API is a real challenge because of the 'mystery' behaviour with special button names and inconsistent behaviours/restrictions (example: I can't for the life of me figure out why NEEO would care whether my device has a number pad or not. What business is it of yours to say that a music streamer — which is not a TV, nor DVB, nor TUNER — can't have number buttons?)

**Comment by neophob** [comment]
Thanks @isolationism. Ok I could reproduce your issue now. The keymapping for the DVD devicetype is in fact not optimal. I'll update the docs in the next release, in the meantime a workaround:

- for DVD you need to define the buttons `CURSOR ENTER`, `PREVIOUS` and `NEXT`.
- if you don't define `PREVIOUS` and `NEXT` then the remote is mapped to the `ENTER`

Let me know if that fixed your issue and thanks for the hint about missing doc

**Comment by neophob** [comment]
@isolationism any feedback from you?

**Comment by isolationism** [comment]
Sorry, I don't have time to play with this on a daily basis, but wouldn't it have been better to leave the ticket open until you actually addressed the documentation shortcoming?
