### ISSUE TITLE
[feature request] Create widgets “grouping” some added controls

### ISSUE THREAD

**Issue by oscarabilleira** [NEEOInc/neeo-sdk#60]
Hi

Actually we can add individual “controls” using SDK that latter we can add into a reciepe as a shortcut. 
If you want to add a group added controls, in a certain order , you have to add latter one by one.
It will be great if we could "group" some added controls into a widget and so that later you can add a widget with all the controls.

**Comment by pfiaux** [comment]
If I understand correctly you want to create new widgets from a given set of controls, if that's correct it should be already covered by #20
