### ISSUE TITLE
Is posible to add “lists” as control?

### ISSUE THREAD

**Issue by oscarabilleira** [NEEOInc/neeo-sdk#61]
Is posible to add a list like is used here?

<img width="274" alt="captura de pantalla 2017-12-31 a las 11 05 41" src="https://user-images.githubusercontent.com/4652774/34460833-d0170dbe-ee1a-11e7-956a-8b6edf80463f.png">

**Comment by neophob** [comment]
definitive yes, is in the backlog

**Comment by oscarabilleira** [comment]
Great!! I hope we can use it soon 😉

**Comment by pfiaux** [comment]
duplicate of #8
