### ISSUE TITLE
Slider is not updated on the Remote (Audio Device)

### ISSUE THREAD

**Issue by clegendre** [NEEOInc/neeo-sdk#62]
Hello,
Discovered when building an Audio driver for SqueezeBox. 
The slider position is not updated on the remote for an Audio Device.

Repro: 
- Add an Audio Device with a slider. 
- Updates the slider value. 
- On the NEEO App, slider is at the correct position. 
- On the Remote slider stays at 0.

BTW, the documentation of the slider does not reflect the SDK implementation. The setter value is the second parameter, the first value is a strange "default" string.

**Comment by neophob** [comment]
thanks @clegendre for your report. can you share your code to reproduce the issue?

**Comment by clegendre** [comment]
Maybe you can checkout the driver I'm working on https://github.com/clegendre/neeo_driver_squeezebox but it needs a Squeezebox setup to work...

**Comment by neophob** [comment]
I'll take a look, thanks @clegendre

**Comment by neophob** [comment]
meanwhile, @clegendre if you have some logs with enabled DEBUG (DEBUG="*") can you post that here too?

**Comment by clegendre** [comment]
Attached you'll find a log of a notification targetting the slider.

[debug_post_notification.log](https://github.com/NEEOInc/neeo-sdk/files/1602026/debug_post_notification.log)

**Comment by neophob** [comment]
Hi @clegendre 

it looks like you don't send any slider updates at all. See the lifx example how to use the slider: https://github.com/NEEOInc/neeo-sdk-examples/blob/master/lib/device/lifx-local/index.js#L8

cheers

**Comment by clegendre** [comment]
Hi, that is not correct, notifications are sent to the brain:
```javascript
if( this._shouldSendUpdate('duration'))
    this.sendComponentUpdate({ uniqueDeviceId, component: 'duration', value });
```
And the debug log show this...

```  neeo:device:device notification { uniqueDeviceId: 'default',
  neeo:device:device   component: 'duration',
  neeo:device:device   value: 20.850987784070362 } +983ms
  neeo:device:brain:BrainIndex notificationKey '6354448378889240576:DURATION_SENSOR' +7ms
```
The slider is updated on the NEEO iOS app, but not on the remote: this is the issue. 

You should reopen this issue.

**Comment by clegendre** [comment]
You were right, the version of the code on github of the Squeeze driver didn't not send an update of the slider. 
It dit when I opened this issue, then an update to manage a cache break this ; I've just push the version that work. 
By the way, this sill NOT work on the Remote only on the App.

**Comment by clegendre** [comment]
Even if you haven't reopen the issue, it still does exists.
I think this is due to the fact that the driver is sending to much events to the remote, I've encoutered the same issue with another driver for IP Camera. 
I'll open a new issue to track this...

**Comment by cro13** [comment]
Hi, please update your NEEO, a new update was released today and let us know if this happens again.

**Comment by pfiaux** [comment]
Considering this as solved.
