### ISSUE TITLE
Records Button missing since last Update

### ISSUE THREAD

**Issue by carp3-noctem** [NEEOInc/neeo-sdk#63]
Hey NEEO,
since the Last SDK Update, the Record Button went missing. I try to recode it, but it doesn't work. 
.addButtonGroup('Record') - doesn't show the Record on the Remote or the App

Kind Regards
Markus

**Comment by neophob** [comment]
Hi @carp3-noctem 

So you update the SDK to v0.48.13 - now the "Record" button group is not visible anymore?

Which Brain version do you use? Can you post your example code?

**Comment by carp3-noctem** [comment]
Yes, i use my latest Enigma2 Driver Code and the latest Available Public and Beta doesn't show the Button anymore.
For the Code you can Visit https://github.com/carp3-noctem/neeo-driver-enigma2

**Comment by carp3-noctem** [comment]
Rechecked the Shortcuts, if i can choose it from there, but also no Button for MY RECORDINGS or RECORD so i think the Button Group 'Record' is gone.

**Comment by bdauria** [comment]
Fixed in 0.49.2

**Comment by carp3-noctem** [comment]
@bdauria is it neccessary to readd the device? because the Button is not yet available on my NEEO and i'm on a higher version

**Comment by bdauria** [comment]
@carp3-noctem Yes, you might need to re-add the device.
