### ISSUE TITLE
Starting with Node Docker image not working

### ISSUE THREAD

**Issue by benzman81** [NEEOInc/neeo-sdk#65]
I get an error: ERROR! BRAIN_NOT_REACHABLE

I used the simple Accessory as sample.

Docker is started with:

`docker run --name=neeo-http -d --restart=on-failure:3 --net=host -p 3000:3000 -p 6336:6336 -v /volume1/docker/neeo-http:/usr/src/app -w /usr/src/app node:8.9.4 node index.js --loglevel=debug`

Is there anything special needed for communication?

**Comment by benzman81** [comment]
Just to add: The discovery works and shows correct ip but right after that, the above error gets raised.

**Comment by neophob** [comment]
can you share a reproducible project?

**Comment by benzman81** [comment]
I simply used the nee-sdk-examples/lib/simpleAccessory and started it with docker on my NAS. Didn't work. Today I tested using the IP and not the discovery and it works like a charm. Only with discovery it doesn't work with docker on my NAS. Maybe because it has two network interfaces (read something like this somewhere)?

**Comment by neophob** [comment]
can try applying this patch https://github.com/NEEOInc/neeo-sdk/pull/39?

**Comment by benzman81** [comment]
nope, didn't help

**Comment by neophob** [comment]
well let me help you, please post the output with enabled debug, so instead `docker ... node index.js 
 ...` use `docker ... DEBUG="*" node index.js ...` and past the complete output

**Comment by benzman81** [comment]
Here is the output (without the patch). Look like it cannot resolve the hostname. I also tried the docker "--dns" option with my router as dns server, but it didn't change the output. Rename the file to html for best visibility.

[neeo-http-2.txt](https://github.com/NEEOInc/neeo-sdk/files/1670085/neeo-http-2.txt)

**Comment by cro13** [comment]
This should work now. Please use the multiInterface functionality in the SDK.
