### ISSUE TITLE
alwaysOn capability doesn't seem to work for devices discovered via `enableDiscovery` callback

### ISSUE THREAD

**Issue by bpruessm** [NEEOInc/neeo-sdk#66]
I was trying to use the `alwaysOn` capability, but it seems that it's not being propagated to devices that are discovered.

**Comment by bdauria** [comment]
I couldn't reproduce with 0.49.2.

Which version of the SDK are you using?

Can you also show some code where the issue occur?

**Comment by bdauria** [comment]
Can you be a bit more specific about the issue, and also show some code to reproduce it?

**Comment by neophob** [comment]
close because no feedback, feel free to reopen @bpruessm if this is still an issue.
