### ISSUE TITLE
addSwitch(): setter called with newValue being a string instead of a boolean

### ISSUE THREAD

**Issue by hoschid** [NEEOInc/neeo-sdk#68]
I added a switch to a device as described in the SDK documentation:
 `.addSwitch(
  { name: 'example-switch', label: 'my switch' },
  { setter: (newValue) => switchState = newValue, getter: () => switchState ) }
 )`
When I press the this switch the setter function is called with `newValue` as an argument. As the switch can only be on or off I would expect `newValue` to be a boolean but it seems to be a string with the value "true" or "false".

**Comment by pfiaux** [comment]
Makes sense it should be a Boolean. This will be a breaking change depending on how the SDK device callback is implemented.

**Comment by bdauria** [comment]
Will be fixed in the next version of the SDK.
