### ISSUE TITLE
State notifications broken with multi device drivers.

### ISSUE THREAD

**Issue by nklerk** [NEEOInc/neeo-sdk#72]
With multiple devices in one driver, state notifications are sent to the last added device adapter.

As example->
devices: [dshd, ds4k, dssk]

All notifications are sent to dssk even though for instance the update is meant for a device added as dshd.

**Comment by bdauria** [comment]
Issue not directly related to the SDK but to its use in https://github.com/nklerk/neeo_driver-DreamScreen/blob/master/dreamscreencontroller.js

@nklerk feel free to re-open if you are not able to fix it there.
