### ISSUE TITLE
startServer fails due to unresolvable host

### ISSUE THREAD

**Issue by barnabycourt** [NEEOInc/neeo-sdk#77]
I am using discovery feature to find the brain on my network. This was working well until recently. Lately the connection to the brain has been timing out if I use discovery. 

If I print out the brain information I see the following:
`{ name: 'NEEO Theater',
  host: 'NEEO-b23d007d.local',
  port: 3000,
  version: '0.49.10-20180116-9347090-0420-125452',
  region: 'US',
  iparray: [ '192.168.1.169' ] }`

The problem is that the hostname discovered is not resolvable on my network. If I override the host value with the value from the first entry in the iparray everything starts up & registers properly. For example, in order to work around this I manually set `brain.host = brain.iparray[0];` before calling `neeoapi.startServer(...)` in my driver code.

**Comment by neophob** [comment]
Which SDK version do you use, the v0.49 version or the @next branch (v0.50)?

**Comment by barnabycourt** [comment]
I am using the current stable v0.49

**Comment by neophob** [comment]
Well it should work with with 0.49, can you share the code that you think does not work as it should?

**Comment by barnabycourt** [comment]
The log from when it failed can be found at https://gist.github.com/barnabycourt/2d2347391894878560439a63f654864a

The corresponding log from when I overwrote the host with the IP address can be found at: 
https://gist.github.com/barnabycourt/29d45872c0ecc5535e4a19701f776c05

It appears to be something going sideways in the brain register where the discovered hostname being returned by the brain via ssdp is not actually resolvable on the network even though the IP address works fine for connecting.

**Comment by neophob** [comment]
Thanks @barnabycourt for the logs. The relevant line is `getaddrinfo ENOTFOUND neeo-b23d007d.local neeo-b23d007d.local:3000` -> which means the host cannot resolve mdns names (.local suffix). Some input:

- What OS do you use (also check out https://github.com/NEEOInc/neeo-sdk#prerequisite)
- is the NEEO Brain and the host that runns the SDK in the same subnet?

**Comment by barnabycourt** [comment]
OS: Windows 10 Home, Version 1803, Build 17134.48. I have Itunes installed & the bonjour service is running. 
 
The NEEO Brain & the server are both connected to the same wired network / subnet though the neeo is connected to the wireless network as well. The wireless network is on a the same subnet. 

The brain is receiving the IP address 192.168.1.169 from the wired network and 192.168.1.199 from the wireless network. 

The SSDP discovery is returning the IP address from the wired network but not the wireless network.

**Comment by neophob** [comment]
what happens if you execute `ping neeo-b23d007d.local` does it work? because if the os has trouble to resolve the dns name it wont succeed. however the sdk can do the bonjour resolution.

**Comment by neophob** [comment]
ah and another hint, there are some access points that split the multicast subnet for the 2.4 and 5ghz network. maybe theres an `enable upnp` option on your ap

**Comment by barnabycourt** [comment]
I am able to ping via the IP address but I am unable to ping via the `neeo-b23d007d.local` hostname. I am using a google fiber box as my router so I have minimal control over it but I am using upnp with other applications without trouble.

**Comment by neophob** [comment]
that means mdns resolution does not work (might be the router or an issue with mdns on windows), as a work around you can use the first ip address (see hint above).
ill close this ticket for now, as there`s nothing we can do in the sdk to resolve the mdns name.

as additional hint you could try to run the sdk on another host or connect the brain via ethernet
