### ISSUE TITLE
listItem.actionIdentifier can't handle special characters.

### ISSUE THREAD

**Issue by nklerk** [NEEOInc/neeo-sdk#83]
Inputting special characters into actionIdentifier will crash the list feature on TR2
` actionIdentifier = '{"action":"x","id":"y"'`

Inputting special characters into actionIdentifier for deviding parameters will result in no action event receiving in the driver. tried:
` actionIdentifier = 'musicAlbum|6336'`
` actionIdentifier = 'musicAlbum:6336'`
` actionIdentifier = 'musicAlbum;6336'`

the following action identifier works normally:
` actionIdentifier = 'musicAlbum6336'`

**Comment by neophob** [comment]
fixed in the latest version, thanks for reporting @nklerk

**Comment by nklerk** [comment]
Sorry but is this fixed, will this be fixed or expected behavior?
