### ISSUE TITLE
Support DropDown lists

### ISSUE THREAD

**Issue by tmrobert8** [NEEOInc/neeo-sdk#84]
Now that we have list in the SDK - would be great to be able to create a drop down list (ie a field [string or text] that support a list of options [that have a label and value] that can be chosen by the user via a drop down or via a list [like on an iphone]).

**Comment by pfiaux** [comment]
Can you clarify where the feature would be used? I think this could already be done in lists by navigating to a sub list with the desired options. Or is that something you would use outside of lists as a shortcut for example?

**Comment by tmrobert8** [comment]
The difference is that it's a compact way to both show current state of an item and to provide navigation for that item.

Example: in Russound (whole house audio), I have a 'source'.  The 'source' is a number between 1 and 5 (on my system, but it can go up to 12).  Source #1 is AM/FM, Source #2 is a Pandora, Source #3 is Spotify, Source #4 is Airplay, Source #5 is general streaming (tunein, etc).

Right now I have this represented as a text label (showing current state) and 5 buttons (to select one of them).  Side note - I'd still love image buttons to show a pandora image, spotify image, airplay image, etc rather than the ugly text but that issue was closed by Michael awhile back - have lotsa uses for that still.

With the lists - I could change it to a text label (showing current state) and a list to navigate - but it's not a very compact way of showing them.  If I had a drop down - it could show the current source and then allow me to select a new source.  

As a suggestion - you could do it with your current UI by allowing a text label be 'clickable' and bring up a sublist.  That way I could define by source as a label, tap on it and the list of options show up...

**Comment by pfiaux** [comment]
OK I see how the select/option type of component would fit for this use case, basically:
* A text/image component that can be updated (text label for current source)
* A click even that shows the options (currently buttons, but ideally triggered by click on the component above)
* A set of options, one click to select and close (currently buttons, lists could work as well)

**Improved list or select component**
I wonder if we could reach this goal with lists if we were to change it as follows:
* New callback/parameter to close list on item select
* Callback similar to label for dynamically changing the directory name

**Image buttons**
Lists currently support images and we also plan to add the favorites functionality (#52), we'll take a look at the other use cases after favorites are implemented.

**Comment by neophob** [comment]
quite similar to #111 and #19 - thus closing this ticket.
