### ISSUE TITLE
Listview top bar is overlapping list content.

### ISSUE THREAD

**Issue by nklerk** [NEEOInc/neeo-sdk#87]
Tested on a iPhone X, The top bar of the list component is overlapping the list content.
Example: https://www.youtube.com/watch?v=LQV6Wi-5-CE

**Comment by MichaelKohler** [comment]
I'll have a look.

**Comment by nklerk** [comment]
When tested with an iPhone SE the header is as expected so probably an iPhone X only EUI issue and not a SDK Issue.

**Comment by neophob** [comment]
@nklerk do you mind take a look if this is still an issue with the latest version?

**Comment by nklerk** [comment]
sorry, missed this one. looks good now.

**Comment by MichaelKohler** [comment]
Perfect, thanks for the update!
