### ISSUE TITLE
Listview reloads title in between the List

### ISSUE THREAD

**Issue by carp3-noctem** [NEEOInc/neeo-sdk#89]
When using the reload of parts of long lists, the Title of the lists gets displayed within the list right on top of the later loaded entrys when using it via an sdk driver e.g. KODI Implementation from @nklerk

**Comment by carp3-noctem** [comment]
This only happens, when you scroll faster to the end of the list, then the reload of new items is fullfilled.

**Comment by MichaelKohler** [comment]
Hi Markus, thanks for reporting this. Is there any chance you could make a video of this? I'm not sure I understand exactly when that happens. :/

**Comment by carp3-noctem** [comment]
Find a Picture at:
https://drive.google.com/file/d/1FyYhgeGIHTpyh1XqSh10Q51-bYd_69KJ/view?usp=sharing
There you see the Filter (Top of the List Entry) was reloaded in the mid of the list, if you still require a video, i try to record one.

**Comment by MichaelKohler** [comment]
Oh, I see. From a quick look at @nklerk's code, this seems to be a driver issue, not an SDK issue: https://github.com/nklerk/neeo_driver-kodi/blob/master/devices/kodi/BrowserService/kodi-browserService-movies.js#L49

What is happening here is that we call the browse function again when loading the next part, with an offset. If the driver responds with a list that has a header in it, we will display it. So IMHO @nklerk should check for the offset > 0 and not add the filter and header in that case. Niels, do you agree?

**Comment by nklerk** [comment]
This is a bug in my code. Will be fixed...

**Comment by MichaelKohler** [comment]
Thanks a lot :)

**Comment by nklerk** [comment]
It’s fixed
