### ISSUE TITLE
URL encoded capabilitie names.

### ISSUE THREAD

**Issue by nklerk** [NEEOInc/neeo-sdk#9]
The name value of capabilities get URL encoded, this results in a crash of the adapter when the capabilitie is used at the app or remote.

The device adapter and capabilities get delivered via json and wont need URL encoded names.

**Comment by neophob** [comment]
This issue is resolved and will be released shortly (post v0.36.0).

I close this issue, feel free to reopen if next release (Brain and SDK) does not resolve this issue!
