### ISSUE TITLE
[Feature request] Custom driver + custom icon

### ISSUE THREAD

**Issue by Webunity** [NEEOInc/neeo-sdk#94]
My custom driver is exposed as DVB, but i really would like it to show a TV icon, even better, i would like to have full control of the icon.. Although the documentation mentions .setIcon('tv') this is not in the supported list of icons yet (bug in docs?)

So i have 3 ideas, i know which one i would like...

1. Allow all icons which are in SetType
2. Allow the driver to expose a custom icon (base64 transparent png?) e.g. setIcon('<base64>')
3. Go even further; allow the SDK to automatically update icons? e.g. SDK.updateIcon(deviceId, <base64) to show for example power state changes?

Can this be put on the backlog?

**Comment by Webunity** [comment]
@neophob Because my 'tv' is hidden; if i watch TV i will actually turn on my CBL/SAT box. This icon now looks thesame like the radio icon, which i don't like.. :) The .setIcon('tv') is in the javadoc above the setIcon function.

**Comment by carp3-noctem** [comment]
Should be doable for all recipes and things, regardless if it is a SDK or direct use. The more a user can do, the happier he will be with the product, at least this is my finding when it comes to customisation request.

**Comment by neophob** [comment]
We will track this in our internal backlog, does not make sense to keep this open here.

Thanks for the input @carp3-noctem
